# clip the gradient to have l2 norm at most this value
gradient_clip_val: 10.0

# lr schedule shape and scale
lr_warmup: 0.1
lr_decay: linear
lr: 0.0003
grad_schedule: False

beta1: 0.9
beta2: 0.999

use_max: False

weight_decay: 0.01
batch_size: 4 # number of examples placed on each GPU

# options for mechanic
mechanize: False
mech_lambda: 0.01
# whether to apply the schedule before mechanic (True) or after mechanic (False)
bake_schedule: True

name: "adamw"

momentum: 0.9


